---
- name: Local Backup Play
  hosts: rtr1
  gather_facts: true
  tasks:
    - name: Create time stamp for play
      ansible.builtin.set_fact:
        datetime: "{{ lookup('pipe', 'date +%Y-%m-%d-%H-%M') }}"
      delegate_to: localhost
      delegate_facts: true
      run_once: true

    - name: Network Backup and Resource Manager
      ansible.builtin.include_role:
        name: network.backup.run
      vars:
        operation: backup
        type: full
        data_store:
          local: "/home/rothakur/ansible-collections/collections/ansible_collections/network/backup/store/"
          backup_file_name: "{{ hostvars['localhost'].datetime }}"
